-- supabase/migrations/00000000000000_initial_schema.sql

-- Enable pgcrypto for UUID generation
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- User profiles
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  name text,
  avatar_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Registered devices
CREATE TABLE public.devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  device_name text NOT NULL DEFAULT 'My Plant',
  device_uid text UNIQUE NOT NULL,
  firmware_version text,
  status text DEFAULT 'offline' CHECK (status IN ('online','offline')),
  last_seen timestamptz,
  created_at timestamptz DEFAULT now()
);

-- Time-series sensor data
CREATE TABLE public.sensor_readings (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  device_id uuid REFERENCES public.devices(id) ON DELETE CASCADE,
  temperature real,
  humidity real,
  moisture real,
  pump_status boolean DEFAULT false,
  mode text DEFAULT 'manual' CHECK (mode IN ('auto','manual')),
  created_at timestamptz DEFAULT now()
);

-- Alerts generated by the system
CREATE TABLE public.alerts (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  device_id uuid REFERENCES public.devices(id) ON DELETE CASCADE,
  severity text NOT NULL CHECK (severity IN ('critical','warning','info')),
  title text NOT NULL,
  message text,
  read boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- Activity events
CREATE TABLE public.events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  device_id uuid REFERENCES public.devices(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  message text,
  created_at timestamptz DEFAULT now()
);

-- Device Commands (Polling Queue)
CREATE TABLE public.device_commands (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  device_id uuid REFERENCES public.devices(id) ON DELETE CASCADE,
  command text NOT NULL,
  executed boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- Indexes
CREATE INDEX idx_sensor_readings_device_time ON public.sensor_readings(device_id, created_at DESC);
CREATE INDEX idx_alerts_device_time ON public.alerts(device_id, created_at DESC);
CREATE INDEX idx_events_device_time ON public.events(device_id, created_at DESC);
CREATE INDEX idx_commands_device_executed ON public.device_commands(device_id, executed);

-- Realtime
alter publication supabase_realtime add table public.sensor_readings;
alter publication supabase_realtime add table public.alerts;
alter publication supabase_realtime add table public.events;

-- RLS (Row Level Security) Setup
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_commands ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Devices Policies
CREATE POLICY "Users can view own devices" ON public.devices FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own devices" ON public.devices FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own devices" ON public.devices FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own devices" ON public.devices FOR DELETE USING (auth.uid() = user_id);

-- Sensor Readings Policies
CREATE POLICY "Users can view own sensor readings" ON public.sensor_readings FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.devices WHERE devices.id = sensor_readings.device_id AND devices.user_id = auth.uid())
);
-- Devices insert via Service Role Key (no policy needed for service role)

-- Alerts Policies
CREATE POLICY "Users can view own alerts" ON public.alerts FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.devices WHERE devices.id = alerts.device_id AND devices.user_id = auth.uid())
);
CREATE POLICY "Users can update own alerts" ON public.alerts FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.devices WHERE devices.id = alerts.device_id AND devices.user_id = auth.uid())
);

-- Events Policies
CREATE POLICY "Users can view own events" ON public.events FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.devices WHERE devices.id = events.device_id AND devices.user_id = auth.uid())
);

-- Commands Policies
CREATE POLICY "Users can view own commands" ON public.device_commands FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.devices WHERE devices.id = device_commands.device_id AND devices.user_id = auth.uid())
);
CREATE POLICY "Users can insert own commands" ON public.device_commands FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.devices WHERE devices.id = device_commands.device_id AND devices.user_id = auth.uid())
);
